#!/bin/sh
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Should-Start: $named
# Should-Stop: $named
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Tomcat.
# Description: Start the Tomcat servlet engine.
### END INIT INFO
# Tomcat  init-script
exec > /tmp/tcat.log 2>&1
CATALINA_HOME=/home/pi/apache-tomcat-7.0.62
export CATALINA_HOME
JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH
case $1 in
 start)
 sh $CATALINA_HOME/bin/startup.sh
 echo "tomcat7 started successfully"
 ;;
 stop)
 sh $CATALINA_HOME/bin/shutdown.sh
 echo "tomcat7 stoped successfully"
 ;;
 restart)
 sh $CATALINA/bin/shutdown.sh
 sh $CATALINA/bin/startup.sh
 echo "tomcat7 restarted successfully"
 ;;
 *)
 sh $CATALINA/bin/startup.sh
 echo "tomcat7 started successfully"
 ;;
 esac
exit 0
